# Generated by Django 5.0 on 2023-12-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=231)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('favourite_anime', models.CharField(max_length=100)),
            ],
        ),
    ]
