# Generated by Django 5.0 on 2023-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeding_options_alter_feeding_date_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(),
        ),
    ]
