# Generated by Django 5.0 on 2023-12-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_owner_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Creator',
        ),
    ]
